1. Data Preparation

1.1 Import the Libraries & Data

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [22]:
from google.colab import files
uploaded = files.upload()

Saving dataset_ott.csv to dataset_ott.csv

In [23]:
data = pd.read_csv('dataset_ott.csv')
data.head()

,Source.Decimal,Source.IP,AMAZON.FLOWS,NETFLIX.FLOWS,YOUTUBE.FLOWS,AMAZON.FLOW.DURATION.MEAN,NETFLIX.FLOW.DURATION.MEAN,YOUTUBE.FLOW.DURATION.MEAN,AMAZON.AVG.PACKET.SIZE,NETFLIX.AVG.PACKET.SIZE,YOUTUBE.AVG.PACKET.SIZE,AMAZON.FLOW.BYTES.PER.SEC,NETFLIX.FLOW.BYTES.PER.SEC,YOUTUBE.FLOW.BYTES.PER.SEC,USER.GROUP
0,3232238082,192.168.10.2,0,0,68,0.00,0.0,35723528.19,0.000000,0.0,311.632202,0.000000,0.0,1.544873e+06,High Consumption
1,3232238083,192.168.10.3,32,0,3,18777150.22,0.0,72796138.00,341.269103,0.0,56.418478,275469.896900,0.0,1.558457e+04,High Consumption
2,3232238084,192.168.10.4,47,0,281,67758322.17,0.0,37702770.81,260.271911,0.0,373.202859,7181.632488,0.0,1.112080e+05,High Consumption
3,3232238085,192.168.10.5,0,0,1,0.00,0.0,51264355.00,0.000000,0.0,149.120000,0.000000,0.0,1.454422e+02,High Consumption
4,3232238086,192.168.10.6,0,0,0,0.00,0.0,0.00,0.000000,0.0,0.000000,0.000000,0.0,0.000000e+00,Medium Consumption

Descriptive Analysis

In [24]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1581 entries, 0 to 1580
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Source.Decimal              1581 non-null   int64
 1   Source.IP                   1581 non-null   object
 2   AMAZON.FLOWS                1581 non-null   int64
 3   NETFLIX.FLOWS               1581 non-null   int64
 4   YOUTUBE.FLOWS               1581 non-null   int64
 5   AMAZON.FLOW.DURATION.MEAN   1581 non-null   float64
 6   NETFLIX.FLOW.DURATION.MEAN  1581 non-null   float64
 7   YOUTUBE.FLOW.DURATION.MEAN  1581 non-null   float64
 8   AMAZON.AVG.PACKET.SIZE      1581 non-null   float64
 9   NETFLIX.AVG.PACKET.SIZE     1581 non-null   float64
 10  YOUTUBE.AVG.PACKET.SIZE     1581 non-null   float64
 11  AMAZON.FLOW.BYTES.PER.SEC   1581 non-null   float64
 12  NETFLIX.FLOW.BYTES.PER.SEC  1581 non-null   float64
 13  YOUTUBE.FLOW.BYTES.PER.SEC  1581 non-null   float64
 14  USER.GROUP                  1581 non-null   object
dtypes: float64(9), int64(4), object(2)
memory usage: 185.4+ KB

In [25]:
data.describe()

,Source.Decimal,AMAZON.FLOWS,NETFLIX.FLOWS,YOUTUBE.FLOWS,AMAZON.FLOW.DURATION.MEAN,NETFLIX.FLOW.DURATION.MEAN,YOUTUBE.FLOW.DURATION.MEAN,AMAZON.AVG.PACKET.SIZE,NETFLIX.AVG.PACKET.SIZE,YOUTUBE.AVG.PACKET.SIZE,AMAZON.FLOW.BYTES.PER.SEC,NETFLIX.FLOW.BYTES.PER.SEC,YOUTUBE.FLOW.BYTES.PER.SEC
count,1.581000e+03,1581.000000,1581.000000,1581.000000,1.581000e+03,1.581000e+03,1.581000e+03,1581.000000,1581.000000,1581.000000,1.581000e+03,1.581000e+03,1.581000e+03
mean,3.232260e+09,4.796331,0.442125,48.311828,3.913795e+06,3.912564e+05,1.758513e+07,69.554530,5.567533,153.137926,5.054028e+04,3.780268e+03,1.590571e+05
std,1.428966e+04,26.625110,3.571331,127.943602,1.311779e+07,3.841771e+06,2.238634e+07,164.136124,41.557210,202.294632,3.738831e+05,7.105562e+04,8.020286e+05
min,3.232238e+09,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00
25%,3.232246e+09,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00
50%,3.232259e+09,0.000000,0.000000,1.000000,0.000000e+00,0.000000e+00,2.861095e+06,0.000000,0.000000,60.196062,0.000000e+00,0.000000e+00,3.088576e+02
75%,3.232269e+09,1.000000,0.000000,38.000000,1.525600e+04,0.000000e+00,3.663391e+07,42.533678,0.000000,284.163114,9.070163e+00,0.000000e+00,6.368663e+04
max,3.232292e+09,716.000000,58.000000,2368.000000,1.199995e+08,6.411384e+07,1.170851e+08,1921.013699,615.196546,1602.905000,9.000247e+06,2.459551e+06,2.324189e+07

In [26]:
data.columns

Index(['Source.Decimal', 'Source.IP', 'AMAZON.FLOWS', 'NETFLIX.FLOWS',
       'YOUTUBE.FLOWS', 'AMAZON.FLOW.DURATION.MEAN',
       'NETFLIX.FLOW.DURATION.MEAN', 'YOUTUBE.FLOW.DURATION.MEAN',
       'AMAZON.AVG.PACKET.SIZE', 'NETFLIX.AVG.PACKET.SIZE',
       'YOUTUBE.AVG.PACKET.SIZE', 'AMAZON.FLOW.BYTES.PER.SEC',
       'NETFLIX.FLOW.BYTES.PER.SEC', 'YOUTUBE.FLOW.BYTES.PER.SEC',
       'USER.GROUP'],
      dtype='object')

1.2 Data Cleansing

In [27]:
drop_col = ['Source.Decimal', 'Source.IP']
data_cleaned = data.drop(columns=drop_col)
data_cleaned.columns

Index(['AMAZON.FLOWS', 'NETFLIX.FLOWS', 'YOUTUBE.FLOWS',
       'AMAZON.FLOW.DURATION.MEAN', 'NETFLIX.FLOW.DURATION.MEAN',
       'YOUTUBE.FLOW.DURATION.MEAN', 'AMAZON.AVG.PACKET.SIZE',
       'NETFLIX.AVG.PACKET.SIZE', 'YOUTUBE.AVG.PACKET.SIZE',
       'AMAZON.FLOW.BYTES.PER.SEC', 'NETFLIX.FLOW.BYTES.PER.SEC',
       'YOUTUBE.FLOW.BYTES.PER.SEC', 'USER.GROUP'],
      dtype='object')

In [28]:
#delete the rows with 0 values in all the cols.
data_cleaned = data_cleaned[~(data_cleaned == 0).all(axis=1)]

In [29]:
data_cleaned

,AMAZON.FLOWS,NETFLIX.FLOWS,YOUTUBE.FLOWS,AMAZON.FLOW.DURATION.MEAN,NETFLIX.FLOW.DURATION.MEAN,YOUTUBE.FLOW.DURATION.MEAN,AMAZON.AVG.PACKET.SIZE,NETFLIX.AVG.PACKET.SIZE,YOUTUBE.AVG.PACKET.SIZE,AMAZON.FLOW.BYTES.PER.SEC,NETFLIX.FLOW.BYTES.PER.SEC,YOUTUBE.FLOW.BYTES.PER.SEC,USER.GROUP
0,0,0,68,0.00,0.00,35723528.19,0.000000,0.000000,311.632202,0.000000,0.0,1.544873e+06,High Consumption
1,32,0,3,18777150.22,0.00,72796138.00,341.269103,0.000000,56.418478,275469.896900,0.0,1.558457e+04,High Consumption
2,47,0,281,67758322.17,0.00,37702770.81,260.271911,0.000000,373.202859,7181.632488,0.0,1.112080e+05,High Consumption
3,0,0,1,0.00,0.00,51264355.00,0.000000,0.000000,149.120000,0.000000,0.0,1.454422e+02,High Consumption
4,0,0,0,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.0,0.000000e+00,Medium Consumption
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1576,25,0,35,1714488.76,0.00,28840124.17,271.933210,0.000000,709.322431,97445.890480,0.0,4.050189e+05,High Consumption
1577,0,29,5,0.00,18106824.93,42221798.80,0.000000,126.737898,118.559891,0.000000,108841.1,3.489827e+05,Medium Consumption
1578,0,0,3,0.00,0.00,68725191.33,0.000000,0.000000,79.083835,0.000000,0.0,3.180554e+04,High Consumption
1579,0,0,39,0.00,0.00,52389498.59,0.000000,0.000000,271.981195,0.000000,0.0,1.990379e+04,High Consumption
1580,0,0,0,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.0,0.000000e+00,High Consumption

In [30]:
# Count of 0 values in every column
for col in data_cleaned.columns:
    count = (data_cleaned[col] == 0).sum()
    print(f"The number of 0 values in '{col}' column is: {count}")

The number of 0 values in 'AMAZON.FLOWS' column is: 1182
The number of 0 values in 'NETFLIX.FLOWS' column is: 1540
The number of 0 values in 'YOUTUBE.FLOWS' column is: 754
The number of 0 values in 'AMAZON.FLOW.DURATION.MEAN' column is: 1182
The number of 0 values in 'NETFLIX.FLOW.DURATION.MEAN' column is: 1540
The number of 0 values in 'YOUTUBE.FLOW.DURATION.MEAN' column is: 754
The number of 0 values in 'AMAZON.AVG.PACKET.SIZE' column is: 1182
The number of 0 values in 'NETFLIX.AVG.PACKET.SIZE' column is: 1540
The number of 0 values in 'YOUTUBE.AVG.PACKET.SIZE' column is: 754
The number of 0 values in 'AMAZON.FLOW.BYTES.PER.SEC' column is: 1182
The number of 0 values in 'NETFLIX.FLOW.BYTES.PER.SEC' column is: 1540
The number of 0 values in 'YOUTUBE.FLOW.BYTES.PER.SEC' column is: 754
The number of 0 values in 'USER.GROUP' column is: 0

just ecause netflix have 1404 '0' values out of 1445 rows, we will remove netflix

In [31]:
data_cleaned = data_cleaned.drop(columns=['NETFLIX.FLOWS','NETFLIX.FLOW.DURATION.MEAN','NETFLIX.AVG.PACKET.SIZE','NETFLIX.FLOW.BYTES.PER.SEC'])

In [32]:
#for col in data_cleaned.columns:
    #plt.figure(figsize=(8, 6))  # Adjust figure size if needed
    #sns.histplot(data_cleaned[col], kde=True)  # Include kde for density estimation
    #plt.title(f'Histogram of {col}')
    #plt.xlabel(col)
    #plt.ylabel('Frequency')
    #plt.show()

In [33]:
# Exclude 'USER.GROUP' column and rows with all zeros
columns_to_check = [col for col in data_cleaned.columns if col != 'USER.GROUP']
data_for_median = data_cleaned[columns_to_check]

# Calculate the mean for each column, excluding 0 values
means = data_for_median[data_for_median != 0].mean()

means

AMAZON.FLOWS                  1.900501e+01
YOUTUBE.FLOWS                 9.235913e+01
AMAZON.FLOW.DURATION.MEAN     1.550804e+07
YOUTUBE.FLOW.DURATION.MEAN    3.361801e+07
AMAZON.AVG.PACKET.SIZE        2.756033e+02
YOUTUBE.AVG.PACKET.SIZE       2.927582e+02
AMAZON.FLOW.BYTES.PER.SEC     2.002611e+05
YOUTUBE.FLOW.BYTES.PER.SEC    3.040740e+05
dtype: float64

In [34]:
# Fill 0 values with the calculated means
for col in columns_to_check:
    data_cleaned[col] = data_cleaned[col].replace(0, means[col])

data_cleaned

,AMAZON.FLOWS,YOUTUBE.FLOWS,AMAZON.FLOW.DURATION.MEAN,YOUTUBE.FLOW.DURATION.MEAN,AMAZON.AVG.PACKET.SIZE,YOUTUBE.AVG.PACKET.SIZE,AMAZON.FLOW.BYTES.PER.SEC,YOUTUBE.FLOW.BYTES.PER.SEC,USER.GROUP
0,19.005013,68.000000,1.550804e+07,3.572353e+07,275.603287,311.632202,200261.117905,1.544873e+06,High Consumption
1,32.000000,3.000000,1.877715e+07,7.279614e+07,341.269103,56.418478,275469.896900,1.558457e+04,High Consumption
2,47.000000,281.000000,6.775832e+07,3.770277e+07,260.271911,373.202859,7181.632488,1.112080e+05,High Consumption
3,19.005013,1.000000,1.550804e+07,5.126436e+07,275.603287,149.120000,200261.117905,1.454422e+02,High Consumption
4,19.005013,92.359129,1.550804e+07,3.361801e+07,275.603287,292.758236,200261.117905,3.040740e+05,Medium Consumption
...,...,...,...,...,...,...,...,...,...
1576,25.000000,35.000000,1.714489e+06,2.884012e+07,271.933210,709.322431,97445.890480,4.050189e+05,High Consumption
1577,19.005013,5.000000,1.550804e+07,4.222180e+07,275.603287,118.559891,200261.117905,3.489827e+05,Medium Consumption
1578,19.005013,3.000000,1.550804e+07,6.872519e+07,275.603287,79.083835,200261.117905,3.180554e+04,High Consumption
1579,19.005013,39.000000,1.550804e+07,5.238950e+07,275.603287,271.981195,200261.117905,1.990379e+04,High Consumption
1580,19.005013,92.359129,1.550804e+07,3.361801e+07,275.603287,292.758236,200261.117905,3.040740e+05,High Consumption

1.3 Data Mapping

In [35]:
# Create a mapping for USER.GROUP values
mapping = {
    'High Consumption': 2,
    'Medium Consumption': 1,
    'Low Consumption': 0
}

# Replace the values in the 'USER.GROUP' column using the mapping
data_cleaned['USER.GROUP'] = data_cleaned['USER.GROUP'].replace(mapping)

data_cleaned

<ipython-input-35-6fca7ea897c2>:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data_cleaned['USER.GROUP'] = data_cleaned['USER.GROUP'].replace(mapping)

,AMAZON.FLOWS,YOUTUBE.FLOWS,AMAZON.FLOW.DURATION.MEAN,YOUTUBE.FLOW.DURATION.MEAN,AMAZON.AVG.PACKET.SIZE,YOUTUBE.AVG.PACKET.SIZE,AMAZON.FLOW.BYTES.PER.SEC,YOUTUBE.FLOW.BYTES.PER.SEC,USER.GROUP
0,19.005013,68.000000,1.550804e+07,3.572353e+07,275.603287,311.632202,200261.117905,1.544873e+06,2
1,32.000000,3.000000,1.877715e+07,7.279614e+07,341.269103,56.418478,275469.896900,1.558457e+04,2
2,47.000000,281.000000,6.775832e+07,3.770277e+07,260.271911,373.202859,7181.632488,1.112080e+05,2
3,19.005013,1.000000,1.550804e+07,5.126436e+07,275.603287,149.120000,200261.117905,1.454422e+02,2
4,19.005013,92.359129,1.550804e+07,3.361801e+07,275.603287,292.758236,200261.117905,3.040740e+05,1
...,...,...,...,...,...,...,...,...,...
1576,25.000000,35.000000,1.714489e+06,2.884012e+07,271.933210,709.322431,97445.890480,4.050189e+05,2
1577,19.005013,5.000000,1.550804e+07,4.222180e+07,275.603287,118.559891,200261.117905,3.489827e+05,1
1578,19.005013,3.000000,1.550804e+07,6.872519e+07,275.603287,79.083835,200261.117905,3.180554e+04,2
1579,19.005013,39.000000,1.550804e+07,5.238950e+07,275.603287,271.981195,200261.117905,1.990379e+04,2
1580,19.005013,92.359129,1.550804e+07,3.361801e+07,275.603287,292.758236,200261.117905,3.040740e+05,2

2.Model Evaluation

2.1 Separate features (X) and target variable (y)

In [36]:
X = data_cleaned.drop('USER.GROUP', axis=1)
y = data_cleaned['USER.GROUP']

2.2 Split data into training and testing sets

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

2.3 Model training in different approach

##1st approach

In [38]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score

# Feature scaling (important for some models like SVM)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


# 1. Logistic Regression
logreg_model = LogisticRegression(max_iter=1000) # Increased max_iter
logreg_model.fit(X_train_scaled, y_train)
logreg_pred = logreg_model.predict(X_test_scaled)
print("Logistic Regression:")
print(classification_report(y_test, logreg_pred))
print(f"Accuracy: {accuracy_score(y_test, logreg_pred)}")


# 2. Random Forest
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train) # No need to scale for Random Forest
rf_pred = rf_model.predict(X_test)
print("\nRandom Forest:")
print(classification_report(y_test, rf_pred))
print(f"Accuracy: {accuracy_score(y_test, rf_pred)}")


# 3. Support Vector Machine (SVM)
svm_model = SVC(random_state=42)
svm_model.fit(X_train_scaled, y_train)
svm_pred = svm_model.predict(X_test_scaled)
print("\nSupport Vector Machine:")
print(classification_report(y_test, svm_pred))
print(f"Accuracy: {accuracy_score(y_test, svm_pred)}")

Logistic Regression:
              precision    recall  f1-score   support

           0       0.10      0.02      0.04        92
           1       0.46      0.20      0.28        90
           2       0.41      0.79      0.54       135

    accuracy                           0.40       317
   macro avg       0.32      0.34      0.28       317
weighted avg       0.34      0.40      0.32       317

Accuracy: 0.39747634069400634

Random Forest:
              precision    recall  f1-score   support

           0       0.62      0.95      0.75        92
           1       0.43      0.20      0.27        90
           2       0.74      0.74      0.74       135

    accuracy                           0.65       317
   macro avg       0.60      0.63      0.59       317
weighted avg       0.62      0.65      0.61       317

Accuracy: 0.6466876971608833

Support Vector Machine:
              precision    recall  f1-score   support

           0       0.57      0.92      0.70        92
           1       0.55      0.20      0.29        90
           2       0.75      0.74      0.74       135

    accuracy                           0.64       317
   macro avg       0.62      0.62      0.58       317
weighted avg       0.64      0.64      0.60       317

Accuracy: 0.6403785488958991

The main prolem is our netflix have 97% '0' values & amazon have 70% '0' values

Trying to increase the accuracy

##2nd approach

cleansing the data

In [39]:
drop_col = ['Source.Decimal', 'Source.IP', 'NETFLIX.FLOWS','NETFLIX.FLOW.DURATION.MEAN','NETFLIX.AVG.PACKET.SIZE','NETFLIX.FLOW.BYTES.PER.SEC']
data1 = data.drop(columns=drop_col)
data1.columns

Index(['AMAZON.FLOWS', 'YOUTUBE.FLOWS', 'AMAZON.FLOW.DURATION.MEAN',
       'YOUTUBE.FLOW.DURATION.MEAN', 'AMAZON.AVG.PACKET.SIZE',
       'YOUTUBE.AVG.PACKET.SIZE', 'AMAZON.FLOW.BYTES.PER.SEC',
       'YOUTUBE.FLOW.BYTES.PER.SEC', 'USER.GROUP'],
      dtype='object')

In [40]:
import numpy as np
# Replace 0 values with NaN
data1 = data1.replace(0, np.nan)
data1

,AMAZON.FLOWS,YOUTUBE.FLOWS,AMAZON.FLOW.DURATION.MEAN,YOUTUBE.FLOW.DURATION.MEAN,AMAZON.AVG.PACKET.SIZE,YOUTUBE.AVG.PACKET.SIZE,AMAZON.FLOW.BYTES.PER.SEC,YOUTUBE.FLOW.BYTES.PER.SEC,USER.GROUP
0,NaN,68.0,NaN,35723528.19,NaN,311.632202,NaN,1.544873e+06,High Consumption
1,32.0,3.0,18777150.22,72796138.00,341.269103,56.418478,275469.896900,1.558457e+04,High Consumption
2,47.0,281.0,67758322.17,37702770.81,260.271911,373.202859,7181.632488,1.112080e+05,High Consumption
3,NaN,1.0,NaN,51264355.00,NaN,149.120000,NaN,1.454422e+02,High Consumption
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Medium Consumption
...,...,...,...,...,...,...,...,...,...
1576,25.0,35.0,1714488.76,28840124.17,271.933210,709.322431,97445.890480,4.050189e+05,High Consumption
1577,NaN,5.0,NaN,42221798.80,NaN,118.559891,NaN,3.489827e+05,Medium Consumption
1578,NaN,3.0,NaN,68725191.33,NaN,79.083835,NaN,3.180554e+04,High Consumption
1579,NaN,39.0,NaN,52389498.59,NaN,271.981195,NaN,1.990379e+04,High Consumption
1580,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,High Consumption

Imputation technique to reduce null values

In [41]:
from sklearn.impute import KNNImputer

# Create a copy to avoid modifying the original DataFrame
data1_imputed = data1.copy()

# Select columns for imputation
columns_to_impute = [col for col in data1.columns if col != 'USER.GROUP']

# Initialize KNNImputer
imputer = KNNImputer(n_neighbors=8)  # You can adjust n_neighbors

# Fit and transform the data
data1_imputed[columns_to_impute] = imputer.fit_transform(data1[columns_to_impute])

# Now data1_imputed contains the imputed values
data1_imputed

,AMAZON.FLOWS,YOUTUBE.FLOWS,AMAZON.FLOW.DURATION.MEAN,YOUTUBE.FLOW.DURATION.MEAN,AMAZON.AVG.PACKET.SIZE,YOUTUBE.AVG.PACKET.SIZE,AMAZON.FLOW.BYTES.PER.SEC,YOUTUBE.FLOW.BYTES.PER.SEC,USER.GROUP
0,19.875000,68.000000,1.357368e+07,3.572353e+07,327.942738,311.632202,198325.166225,1.544873e+06,High Consumption
1,32.000000,3.000000,1.877715e+07,7.279614e+07,341.269103,56.418478,275469.896900,1.558457e+04,High Consumption
2,47.000000,281.000000,6.775832e+07,3.770277e+07,260.271911,373.202859,7181.632488,1.112080e+05,High Consumption
3,7.250000,1.000000,2.457986e+07,5.126436e+07,458.848660,149.120000,344311.612398,1.454422e+02,High Consumption
4,19.005013,92.359129,1.550804e+07,3.361801e+07,275.603287,292.758236,200261.117905,3.040740e+05,Medium Consumption
...,...,...,...,...,...,...,...,...,...
1576,25.000000,35.000000,1.714489e+06,2.884012e+07,271.933210,709.322431,97445.890480,4.050189e+05,High Consumption
1577,11.375000,5.000000,2.195418e+07,4.222180e+07,283.391188,118.559891,142565.062427,3.489827e+05,Medium Consumption
1578,4.125000,3.000000,1.911641e+07,6.872519e+07,486.437560,79.083835,122633.249410,3.180554e+04,High Consumption
1579,9.625000,39.000000,1.482647e+07,5.238950e+07,192.698201,271.981195,87470.429963,1.990379e+04,High Consumption
1580,19.005013,92.359129,1.550804e+07,3.361801e+07,275.603287,292.758236,200261.117905,3.040740e+05,High Consumption

Data Mapping

In [42]:
# Create a mapping for USER.GROUP values
mapping = {
    'High Consumption': 2,
    'Medium Consumption': 1,
    'Low Consumption': 0
}

# Replace the values in the 'USER.GROUP' column using the mapping
data1_imputed['USER.GROUP'] = data1_imputed['USER.GROUP'].replace(mapping)

data1_imputed

<ipython-input-42-a57a4e80458c>:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data1_imputed['USER.GROUP'] = data1_imputed['USER.GROUP'].replace(mapping)

,AMAZON.FLOWS,YOUTUBE.FLOWS,AMAZON.FLOW.DURATION.MEAN,YOUTUBE.FLOW.DURATION.MEAN,AMAZON.AVG.PACKET.SIZE,YOUTUBE.AVG.PACKET.SIZE,AMAZON.FLOW.BYTES.PER.SEC,YOUTUBE.FLOW.BYTES.PER.SEC,USER.GROUP
0,19.875000,68.000000,1.357368e+07,3.572353e+07,327.942738,311.632202,198325.166225,1.544873e+06,2
1,32.000000,3.000000,1.877715e+07,7.279614e+07,341.269103,56.418478,275469.896900,1.558457e+04,2
2,47.000000,281.000000,6.775832e+07,3.770277e+07,260.271911,373.202859,7181.632488,1.112080e+05,2
3,7.250000,1.000000,2.457986e+07,5.126436e+07,458.848660,149.120000,344311.612398,1.454422e+02,2
4,19.005013,92.359129,1.550804e+07,3.361801e+07,275.603287,292.758236,200261.117905,3.040740e+05,1
...,...,...,...,...,...,...,...,...,...
1576,25.000000,35.000000,1.714489e+06,2.884012e+07,271.933210,709.322431,97445.890480,4.050189e+05,2
1577,11.375000,5.000000,2.195418e+07,4.222180e+07,283.391188,118.559891,142565.062427,3.489827e+05,1
1578,4.125000,3.000000,1.911641e+07,6.872519e+07,486.437560,79.083835,122633.249410,3.180554e+04,2
1579,9.625000,39.000000,1.482647e+07,5.238950e+07,192.698201,271.981195,87470.429963,1.990379e+04,2
1580,19.005013,92.359129,1.550804e+07,3.361801e+07,275.603287,292.758236,200261.117905,3.040740e+05,2

In [43]:
#feature_eng

In [44]:
# Separate Amazon and YouTube data
amazon_data = data1_imputed[['AMAZON.FLOWS','AMAZON.AVG.PACKET.SIZE','AMAZON.FLOW.DURATION.MEAN','AMAZON.FLOW.BYTES.PER.SEC','USER.GROUP']]


# Now you have two separate DataFrames: amazon_data and youtube_data
print("Amazon Data:")
print(amazon_data.head())

Amazon Data:
   AMAZON.FLOWS  AMAZON.AVG.PACKET.SIZE  AMAZON.FLOW.DURATION.MEAN  \
0     19.875000              327.942738               1.357368e+07
1     32.000000              341.269103               1.877715e+07
2     47.000000              260.271911               6.775832e+07
3      7.250000              458.848660               2.457986e+07
4     19.005013              275.603287               1.550804e+07

   AMAZON.FLOW.BYTES.PER.SEC  USER.GROUP
0              198325.166225           2
1              275469.896900           2
2                7181.632488           2
3              344311.612398           2
4              200261.117905           1

In [45]:
# Separate YouTube data
yt_data = data1_imputed[['YOUTUBE.FLOWS','YOUTUBE.AVG.PACKET.SIZE','YOUTUBE.FLOW.DURATION.MEAN','YOUTUBE.FLOW.BYTES.PER.SEC','USER.GROUP']]


# Now you have two separate DataFrames: amazon_data and youtube_data
print("YOUTUBE Data:")
print(yt_data.head())

YOUTUBE Data:
   YOUTUBE.FLOWS  YOUTUBE.AVG.PACKET.SIZE  YOUTUBE.FLOW.DURATION.MEAN  \
0      68.000000               311.632202                3.572353e+07
1       3.000000                56.418478                7.279614e+07
2     281.000000               373.202859                3.770277e+07
3       1.000000               149.120000                5.126436e+07
4      92.359129               292.758236                3.361801e+07

   YOUTUBE.FLOW.BYTES.PER.SEC  USER.GROUP
0                1.544873e+06           2
1                1.558457e+04           2
2                1.112080e+05           2
3                1.454422e+02           2
4                3.040740e+05           1

In [46]:
yt_data.describe()

,YOUTUBE.FLOWS,YOUTUBE.AVG.PACKET.SIZE,YOUTUBE.FLOW.DURATION.MEAN,YOUTUBE.FLOW.BYTES.PER.SEC,USER.GROUP
count,1581.000000,1581.000000,1.581000e+03,1.581000e+03,1581.000000
mean,93.823986,293.340006,3.350662e+07,3.058179e+05,1.106262
std,120.931324,140.367994,1.489782e+07,7.895160e+05,0.834444
min,1.000000,10.091644,3.370050e+04,1.199011e+01,0.000000
25%,28.000000,260.232494,3.153587e+07,5.305499e+04,0.000000
50%,92.359129,292.758236,3.361801e+07,3.040740e+05,1.000000
75%,92.359129,303.079261,3.744634e+07,3.040740e+05,2.000000
max,2368.000000,1602.905000,1.170851e+08,2.324189e+07,2.000000

In [47]:
#creating list for model selection
model_acc = []

Using Logistic regression, SVM & Radom Forest

In [48]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score

# Separate features (X) and target variable (y)
X = yt_data.drop('USER.GROUP', axis=1)
y = yt_data['USER.GROUP']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Feature scaling (important for some models like SVM)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


# 1. Logistic Regression
logreg_model = LogisticRegression(max_iter=1000) # Increased max_iter
logreg_model.fit(X_train_scaled, y_train)
logreg_pred = logreg_model.predict(X_test_scaled)
print("Logistic Regression:")
print(classification_report(y_test, logreg_pred))
print(f"Accuracy: {accuracy_score(y_test, logreg_pred)}")
model_acc.append(accuracy_score(y_test, logreg_pred))


# 2. Random Forest
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train) # No need to scale for Random Forest
rf_pred = rf_model.predict(X_test)
print("\nRandom Forest:")
print(classification_report(y_test, rf_pred))
print(f"Accuracy: {accuracy_score(y_test, rf_pred)}")
model_acc.append(accuracy_score(y_test, rf_pred))


# 3. Support Vector Machine (SVM)
svm_model = SVC(random_state=42)
svm_model.fit(X_train_scaled, y_train)
svm_pred = svm_model.predict(X_test_scaled)
print("\nSupport Vector Machine:")
print(classification_report(y_test, svm_pred))
print(f"Accuracy: {accuracy_score(y_test, svm_pred)}")
model_acc.append(accuracy_score(y_test, svm_pred))

Logistic Regression:
              precision    recall  f1-score   support

           0       0.13      0.03      0.05        92
           1       0.42      0.19      0.26        90
           2       0.41      0.77      0.53       135

    accuracy                           0.39       317
   macro avg       0.32      0.33      0.28       317
weighted avg       0.33      0.39      0.32       317

Accuracy: 0.3911671924290221

Random Forest:
              precision    recall  f1-score   support

           0       0.62      0.93      0.74        92
           1       0.50      0.19      0.27        90
           2       0.76      0.81      0.78       135

    accuracy                           0.67       317
   macro avg       0.63      0.64      0.60       317
weighted avg       0.64      0.67      0.63       317

Accuracy: 0.668769716088328

Support Vector Machine:
              precision    recall  f1-score   support

           0       0.54      0.92      0.68        92
           1       0.42      0.22      0.29        90
           2       0.78      0.64      0.71       135

    accuracy                           0.61       317
   macro avg       0.58      0.60      0.56       317
weighted avg       0.61      0.61      0.58       317

Accuracy: 0.6056782334384858

Using Gradient Boosting, Ada Boost, Hist Gradient Boosting

In [49]:
from sklearn.ensemble import GradientBoostingClassifier, AdaBoostClassifier, HistGradientBoostingClassifier

# Separate features (X) and target variable (y)
X = yt_data.drop('USER.GROUP', axis=1)
y = yt_data['USER.GROUP']

# Gradient Boosting Classifier
gb_model = GradientBoostingClassifier(random_state=42)
gb_model.fit(X_train, y_train)
gb_pred = gb_model.predict(X_test)
print("\nGradient Boosting Classifier:")
print(classification_report(y_test, gb_pred))
print(f"Accuracy: {accuracy_score(y_test, gb_pred)}")
model_acc.append(accuracy_score(y_test, gb_pred))

# AdaBoost Classifier
ada_model = AdaBoostClassifier(random_state=42)
ada_model.fit(X_train, y_train)
ada_pred = ada_model.predict(X_test)
print("\nAdaBoost Classifier:")
print(classification_report(y_test, ada_pred))
print(f"Accuracy: {accuracy_score(y_test, ada_pred)}")
model_acc.append(accuracy_score(y_test, ada_pred))

# HistGradientBoostingClassifier
hist_gb_model = HistGradientBoostingClassifier(random_state=42)
hist_gb_model.fit(X_train, y_train)
hist_gb_pred = hist_gb_model.predict(X_test)
print("\nHistGradientBoostingClassifier:")
print(classification_report(y_test, hist_gb_pred))
print(f"Accuracy: {accuracy_score(y_test, hist_gb_pred)}")
model_acc.append(accuracy_score(y_test, hist_gb_pred))

Gradient Boosting Classifier:
              precision    recall  f1-score   support

           0       0.61      0.92      0.74        92
           1       0.49      0.19      0.27        90
           2       0.73      0.78      0.76       135

    accuracy                           0.65       317
   macro avg       0.61      0.63      0.59       317
weighted avg       0.63      0.65      0.61       317

Accuracy: 0.6529968454258676

AdaBoost Classifier:
              precision    recall  f1-score   support

           0       0.61      0.92      0.74        92
           1       0.38      0.07      0.11        90
           2       0.69      0.83      0.75       135

    accuracy                           0.64       317
   macro avg       0.56      0.61      0.53       317
weighted avg       0.58      0.64      0.57       317

Accuracy: 0.6403785488958991

HistGradientBoostingClassifier:
              precision    recall  f1-score   support

           0       0.61      0.93      0.74        92
           1       0.39      0.22      0.28        90
           2       0.74      0.69      0.71       135

    accuracy                           0.63       317
   macro avg       0.58      0.62      0.58       317
weighted avg       0.60      0.63      0.60       317

Accuracy: 0.6277602523659306

##3. Model Selection

In [50]:
# Create a DataFrame to store model accuracy
model_data = {'Model Name': ['Logistic Regression', 'Random Forest', 'Support Vector Machine','Gradient Boosting', 'AdaBoost', 'HistGradientBoosting'],
              'Accuracy': model_acc}
model_df = pd.DataFrame(model_data)
model_df = model_df.sort_values(by='Accuracy', ascending=False)
model_df

               Model Name  Accuracy
1           Random Forest  0.668770
3       Gradient Boosting  0.652997
4                AdaBoost  0.640379
5    HistGradientBoosting  0.627760
2  Support Vector Machine  0.605678
0     Logistic Regression  0.391167

so, our best model is Random Forest. we will use the:

GridSearchCV on Random Forest Classifier(to get best parameters)

In [51]:
from sklearn.model_selection import GridSearchCV

# Separate features (X) and target variable (y)
X = yt_data.drop('USER.GROUP', axis=1)
y = yt_data['USER.GROUP']

# Example using GridSearchCV with RandomForestClassifier for Amazon data
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10]
}

rf_model = RandomForestClassifier(random_state=42)
grid_search = GridSearchCV(estimator=rf_model, param_grid=param_grid, cv=5, scoring='accuracy') # Use 5-fold cross-validation
grid_search.fit(X_train, y_train)

print("Best hyperparameters:", grid_search.best_params_)
print("Best score:", grid_search.best_score_)

best_rf_model = grid_search.best_estimator_
rf_pred = best_rf_model.predict(X_test)
print("\nRandom Forest (with GridSearchCV):")
print(classification_report(y_test, rf_pred))
print(f"Accuracy: {accuracy_score(y_test, rf_pred)}")


# Repeat similar GridSearchCV for other models and datasets (YouTube data, etc.)
grid_search_yt = GridSearchCV(estimator=rf_model, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search_yt.fit(X_train, y_train)

# Example for GradientBoostingClassifier
param_grid_gb = {
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.01, 0.1, 1],
    'max_depth': [3, 5, 7]
}
gb_model = GradientBoostingClassifier(random_state=42)
grid_search_gb = GridSearchCV(estimator=gb_model, param_grid=param_grid_gb, cv=5, scoring='accuracy')
grid_search_gb.fit(X_train, y_train)
print("Best hyperparameters for Gradient Boosting:", grid_search_gb.best_params_)
print("Best score for Gradient Boosting:", grid_search_gb.best_score_)

Best hyperparameters: {'max_depth': 10, 'min_samples_split': 10, 'n_estimators': 200}
Best score: 0.6313413639500596

Random Forest (with GridSearchCV):
              precision    recall  f1-score   support

           0       0.62      0.92      0.74        92
           1       0.53      0.21      0.30        90
           2       0.76      0.81      0.78       135

    accuracy                           0.67       317
   macro avg       0.64      0.65      0.61       317
weighted avg       0.65      0.67      0.63       317

Accuracy: 0.6719242902208202
Best hyperparameters for Gradient Boosting: {'learning_rate': 0.01, 'max_depth': 3, 'n_estimators': 200}
Best score for Gradient Boosting: 0.6416274546709329

#save the model to use

In [52]:
import joblib

# Assuming 'best_rf_model' is your best RandomForestClassifier model from GridSearchCV
joblib.dump(best_rf_model, 'best_rf_model.pkl')

['best_rf_model.pkl']

In [53]:

first_row_group1 = yt_data[yt_data['USER.GROUP'] == 1].iloc[0]
first_row_group1

YOUTUBE.FLOWS                 9.235913e+01
YOUTUBE.AVG.PACKET.SIZE       2.927582e+02
YOUTUBE.FLOW.DURATION.MEAN    3.361801e+07
YOUTUBE.FLOW.BYTES.PER.SEC    3.040740e+05
USER.GROUP                    1.000000e+00
Name: 4, dtype: float64

In [54]:
print(yt_data['YOUTUBE.FLOW.BYTES.PER.SEC'])

0       1.544873e+06
1       1.558457e+04
2       1.112080e+05
3       1.454422e+02
4       3.040740e+05
            ...
1576    4.050189e+05
1577    3.489827e+05
1578    3.180554e+04
1579    1.990379e+04
1580    3.040740e+05
Name: YOUTUBE.FLOW.BYTES.PER.SEC, Length: 1581, dtype: float64

In [55]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, accuracy_score
from sklearn.impute import KNNImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

# Prepare data for RNN
X = yt_data.drop('USER.GROUP', axis=1).values
y = yt_data['USER.GROUP'].values

# Reshape data for LSTM (samples, timesteps, features)
# Assuming each row is a timestep
X = X.reshape(X.shape[0], 1, X.shape[1])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train.reshape(-1, X_train.shape[-1])).reshape(X_train.shape)
X_test = scaler.transform(X_test.reshape(-1, X_test.shape[-1])).reshape(X_test.shape)

# Define the RNN model
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(X_train.shape[1], X_train.shape[2])))
model.add(Dense(1, activation='sigmoid')) # Output layer for classification
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=50, batch_size=32) # Adjust epochs and batch_size

# Evaluate the model
_, accuracy = model.evaluate(X_test, y_test)
print('RNN Accuracy: %.2f' % (accuracy*100))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - accuracy: 0.2897 - loss: 0.6370
Epoch 2/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3167 - loss: 0.5254
Epoch 3/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3029 - loss: 0.3488
Epoch 4/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3051 - loss: 0.1579
Epoch 5/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2898 - loss: -0.1566
Epoch 6/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3040 - loss: -0.4192
Epoch 7/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2799 - loss: -0.9081
Epoch 8/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3062 - loss: -1.3413
Epoch 9/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2831 - loss: -2.2709
Epoch 10/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3105 - loss: -2.7590
Epoch 11/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2978 - loss: -3.4714
Epoch 12/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2895 - loss: -4.4115
Epoch 13/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.2902 - loss: -6.2776
Epoch 14/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2739 - loss: -6.3500
Epoch 15/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3072 - loss: -8.4495
Epoch 16/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.2924 - loss: -8.6895
Epoch 17/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3000 - loss: -12.2251
Epoch 18/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2975 - loss: -12.9264
Epoch 19/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3015 - loss: -15.9075
Epoch 20/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2987 - loss: -15.6586
Epoch 21/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3055 - loss: -19.3120
Epoch 22/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3036 - loss: -20.2062
Epoch 23/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2781 - loss: -24.0558
Epoch 24/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2851 - loss: -24.6929
Epoch 25/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3029 - loss: -24.9563
Epoch 26/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2841 - loss: -30.1498
Epoch 27/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2898 - loss: -29.7123
Epoch 28/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2884 - loss: -34.9252
Epoch 29/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3026 - loss: -34.7042
Epoch 30/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3203 - loss: -37.0687
Epoch 31/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3031 - loss: -42.5025
Epoch 32/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2659 - loss: -49.9528
Epoch 33/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2977 - loss: -41.7828
Epoch 34/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3242 - loss: -44.8309
Epoch 35/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3007 - loss: -52.2733
Epoch 36/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2898 - loss: -58.4007
Epoch 37/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3049 - loss: -64.6044
Epoch 38/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3061 - loss: -60.5089
Epoch 39/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.2903 - loss: -67.4128
Epoch 40/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3004 - loss: -68.5684
Epoch 41/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3114 - loss: -76.7492
Epoch 42/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3051 - loss: -83.7626
Epoch 43/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2830 - loss: -88.4280
Epoch 44/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3221 - loss: -82.9391
Epoch 45/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2972 - loss: -103.2431
Epoch 46/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.2968 - loss: -101.1360
Epoch 47/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2900 - loss: -93.5271
Epoch 48/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2850 - loss: -122.2374
Epoch 49/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3028 - loss: -96.7072
Epoch 50/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.2923 - loss: -99.2881
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.3019 - loss: -132.6811
RNN Accuracy: 28.39

In [56]:
from google.colab import files
files.download('best_rf_model.pkl')